name: desafio-brev-ly

services:
  db:
    container_name: brev-ly-db-postgres
    image: bitnami/postgresql:latest
    restart: unless-stopped
    ports:
      - $POSTGRESQL_PORT:5432
    env_file:
      - .env
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
      - db-volume:/bitnami/postgresql
    networks:
      - db-network
      - app-network

  app:
    depends_on:
      - db
    restart: unless-stopped
    container_name: brev-ly-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $PORT:$PORT
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - app-network

volumes:
  db-volume:
    driver: local

networks:
  db-network:
    driver: bridge
  app-network:
    driver: bridge
